[[drone]]
id = 1
connected_node_ids = [20, 5, 6]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [5,6,33]
pdr = 0.03

[[drone]]
id = 3
connected_node_ids = [7,8,31]
pdr = 0.14

[[drone]]
id = 4
connected_node_ids = [7,8,30,21]
pdr = 0.14

[[drone]]
id = 5
connected_node_ids = [1,2,9,21,22]
pdr = 0.14

[[drone]]
id = 6
connected_node_ids = [1,2,10,31,33]
pdr = 0.14

[[drone]]
id = 7
connected_node_ids = [9,3,4,30,32]
pdr = 0.14

[[drone]]
id = 8
connected_node_ids = [10,3,4,22,23]
pdr = 0.14

[[drone]]
id = 9
connected_node_ids = [5,7,10,22,23]
pdr = 0.14

[[drone]]
id = 10
connected_node_ids = [9,6,8,20]
pdr = 0.14


[[client]]
id = 20
connected_drone_ids = [1,10]
[[client]]
id = 21
connected_drone_ids = [4,5]
[[client]]
id = 22
connected_drone_ids = [5,8,9]
[[client]]
id = 23
connected_drone_ids = [9,8]


[[server]]
id = 30
connected_drone_ids = [7,4]

[[server]]
id = 31
connected_drone_ids = [3,6]

[[server]]
id = 32
connected_drone_ids = [7]

[[server]]
id = 33
connected_drone_ids = [6,2]

